/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saojudas.nuplacar;;

import com.saojudas.nuplacar.DAO.GrupoDAO;
import com.saojudas.nuplacar.DAO.TimeDAO;
import javax.swing.JTable;
import java.util.ArrayList;
import java.util.Collections;


/**
 *
 * @author MatheusBC
 */
public class TelaSimularMataMata extends javax.swing.JFrame {

    /**
     * Creates new form TelaSimularMataMata
     */
    
    private ArrayList<Grupo> grupos = new ArrayList();
    private Campeonato campeonato;
    
    public TelaSimularMataMata(ArrayList<Grupo> grupos) {
        super("Simulação Mata-mata");
        
        initComponents();
        setLocationRelativeTo(null);
        
        this.grupos = grupos;
        this.campeonato = new Campeonato(grupos);
        setValoresIniciaisTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        FaseGruposLabel = new javax.swing.JLabel();
        refazerSimulacaoButton = new javax.swing.JButton();
        avancarButton = new javax.swing.JButton();
        SimularButton = new javax.swing.JButton();
        Time2Jogo1Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Time1Jogo1Label = new javax.swing.JLabel();
        Time1Jogo16Label = new javax.swing.JLabel();
        Time1Jogo9Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Time2Jogo9Label = new javax.swing.JLabel();
        Time2Jogo3Label = new javax.swing.JLabel();
        Time1Jogo2Label = new javax.swing.JLabel();
        Time2Jogo2Label = new javax.swing.JLabel();
        Time1Jogo3Label = new javax.swing.JLabel();
        Time2Jogo4Label = new javax.swing.JLabel();
        Time2Jogo10Label = new javax.swing.JLabel();
        Time1Jogo4Label = new javax.swing.JLabel();
        Time1Jogo10Label = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Time1Jogo13Label = new javax.swing.JLabel();
        Time2Jogo13Label = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Time2Jogo16Label = new javax.swing.JLabel();
        Time1Jogo15Label = new javax.swing.JLabel();
        Time2Jogo15Label = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Time1Jogo11Label = new javax.swing.JLabel();
        Time2Jogo5Label = new javax.swing.JLabel();
        Time1Jogo5Label = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Time1Jogo6Label = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Time2Jogo11Label = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Time1Jogo14Label = new javax.swing.JLabel();
        Time2Jogo6Label = new javax.swing.JLabel();
        Time2Jogo7Label = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        Time1Jogo7Label = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        Time1Jogo8Label = new javax.swing.JLabel();
        Time2Jogo8Label = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Time1Jogo12Label = new javax.swing.JLabel();
        Time2Jogo12Label = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        Time2Jogo14Label = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel24 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(141, 27, 61));

        FaseGruposLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        FaseGruposLabel.setForeground(new java.awt.Color(255, 255, 255));
        FaseGruposLabel.setText("Mata-mata");
        FaseGruposLabel.setMaximumSize(new java.awt.Dimension(142, 48));
        FaseGruposLabel.setMinimumSize(new java.awt.Dimension(142, 48));

        refazerSimulacaoButton.setText("Refazer simulação");
        refazerSimulacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refazerSimulacaoButtonActionPerformed(evt);
            }
        });

        avancarButton.setText("Finalizar");
        avancarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarButtonActionPerformed(evt);
            }
        });

        SimularButton.setText("Voltar para a fase de grupos");
        SimularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimularButtonActionPerformed(evt);
            }
        });

        Time2Jogo1Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo1Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo1Label.setText("Time1");
        Time2Jogo1Label.setAlignmentX(1.0F);
        Time2Jogo1Label.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setOpaque(true);

        Time1Jogo1Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo1Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo1Label.setText("Time1");
        Time1Jogo1Label.setAlignmentX(1.0F);
        Time1Jogo1Label.setOpaque(true);

        Time1Jogo16Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo16Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo16Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo16Label.setText("Time1");
        Time1Jogo16Label.setAlignmentX(1.0F);
        Time1Jogo16Label.setOpaque(true);

        Time1Jogo9Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo9Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo9Label.setText("Time1");
        Time1Jogo9Label.setAlignmentX(1.0F);
        Time1Jogo9Label.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");
        jLabel6.setAlignmentX(1.0F);
        jLabel6.setOpaque(true);

        Time2Jogo9Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo9Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo9Label.setText("Time1");
        Time2Jogo9Label.setAlignmentX(1.0F);
        Time2Jogo9Label.setOpaque(true);

        Time2Jogo3Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo3Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo3Label.setText("Time1");
        Time2Jogo3Label.setAlignmentX(1.0F);
        Time2Jogo3Label.setOpaque(true);

        Time1Jogo2Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo2Label.setText("Time1");
        Time1Jogo2Label.setAlignmentX(1.0F);
        Time1Jogo2Label.setOpaque(true);

        Time2Jogo2Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo2Label.setText("Time1");
        Time2Jogo2Label.setAlignmentX(1.0F);
        Time2Jogo2Label.setOpaque(true);

        Time1Jogo3Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo3Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo3Label.setText("Time1");
        Time1Jogo3Label.setAlignmentX(1.0F);
        Time1Jogo3Label.setOpaque(true);

        Time2Jogo4Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo4Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo4Label.setText("Time1");
        Time2Jogo4Label.setAlignmentX(1.0F);
        Time2Jogo4Label.setOpaque(true);

        Time2Jogo10Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo10Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo10Label.setText("Time1");
        Time2Jogo10Label.setAlignmentX(1.0F);
        Time2Jogo10Label.setOpaque(true);

        Time1Jogo4Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo4Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo4Label.setText("Time1");
        Time1Jogo4Label.setAlignmentX(1.0F);
        Time1Jogo4Label.setOpaque(true);

        Time1Jogo10Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo10Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo10Label.setText("Time1");
        Time1Jogo10Label.setAlignmentX(1.0F);
        Time1Jogo10Label.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("0");
        jLabel16.setAlignmentX(1.0F);
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("0");
        jLabel17.setAlignmentX(1.0F);
        jLabel17.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");
        jLabel18.setAlignmentX(1.0F);
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0");
        jLabel19.setAlignmentX(1.0F);
        jLabel19.setOpaque(true);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("0");
        jLabel20.setAlignmentX(1.0F);
        jLabel20.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("0");
        jLabel21.setAlignmentX(1.0F);
        jLabel21.setOpaque(true);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("0");
        jLabel22.setAlignmentX(1.0F);
        jLabel22.setOpaque(true);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("0");
        jLabel23.setAlignmentX(1.0F);
        jLabel23.setOpaque(true);

        Time1Jogo13Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo13Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo13Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo13Label.setText("Time1");
        Time1Jogo13Label.setAlignmentX(1.0F);
        Time1Jogo13Label.setOpaque(true);

        Time2Jogo13Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo13Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo13Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo13Label.setText("Time1");
        Time2Jogo13Label.setAlignmentX(1.0F);
        Time2Jogo13Label.setOpaque(true);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("0");
        jLabel27.setAlignmentX(1.0F);
        jLabel27.setOpaque(true);

        Time2Jogo16Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo16Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo16Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo16Label.setText("Time1");
        Time2Jogo16Label.setAlignmentX(1.0F);
        Time2Jogo16Label.setOpaque(true);

        Time1Jogo15Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo15Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo15Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo15Label.setText("Time1");
        Time1Jogo15Label.setAlignmentX(1.0F);
        Time1Jogo15Label.setOpaque(true);

        Time2Jogo15Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo15Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo15Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo15Label.setText("Time1");
        Time2Jogo15Label.setAlignmentX(1.0F);
        Time2Jogo15Label.setOpaque(true);

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("0");
        jLabel31.setAlignmentX(1.0F);
        jLabel31.setOpaque(true);

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("0");
        jLabel32.setAlignmentX(1.0F);
        jLabel32.setOpaque(true);

        Time1Jogo11Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo11Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo11Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo11Label.setText("Time1");
        Time1Jogo11Label.setAlignmentX(1.0F);
        Time1Jogo11Label.setOpaque(true);

        Time2Jogo5Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo5Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo5Label.setText("Time1");
        Time2Jogo5Label.setAlignmentX(1.0F);
        Time2Jogo5Label.setOpaque(true);

        Time1Jogo5Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo5Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo5Label.setText("Time1");
        Time1Jogo5Label.setAlignmentX(1.0F);
        Time1Jogo5Label.setOpaque(true);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("0");
        jLabel36.setAlignmentX(1.0F);
        jLabel36.setOpaque(true);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("0");
        jLabel37.setAlignmentX(1.0F);
        jLabel37.setOpaque(true);

        Time1Jogo6Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo6Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo6Label.setText("Time1");
        Time1Jogo6Label.setAlignmentX(1.0F);
        Time1Jogo6Label.setOpaque(true);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("0");
        jLabel39.setAlignmentX(1.0F);
        jLabel39.setOpaque(true);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("0");
        jLabel40.setAlignmentX(1.0F);
        jLabel40.setOpaque(true);

        Time2Jogo11Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo11Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo11Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo11Label.setText("Time1");
        Time2Jogo11Label.setAlignmentX(1.0F);
        Time2Jogo11Label.setOpaque(true);

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("0");
        jLabel42.setAlignmentX(1.0F);
        jLabel42.setOpaque(true);

        Time1Jogo14Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo14Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo14Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo14Label.setText("Time1");
        Time1Jogo14Label.setAlignmentX(1.0F);
        Time1Jogo14Label.setOpaque(true);

        Time2Jogo6Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo6Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo6Label.setText("Time1");
        Time2Jogo6Label.setAlignmentX(1.0F);
        Time2Jogo6Label.setOpaque(true);

        Time2Jogo7Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo7Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo7Label.setText("Time1");
        Time2Jogo7Label.setAlignmentX(1.0F);
        Time2Jogo7Label.setOpaque(true);

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("0");
        jLabel46.setAlignmentX(1.0F);
        jLabel46.setOpaque(true);

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("0");
        jLabel47.setAlignmentX(1.0F);
        jLabel47.setOpaque(true);

        Time1Jogo7Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo7Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo7Label.setText("Time1");
        Time1Jogo7Label.setAlignmentX(1.0F);
        Time1Jogo7Label.setOpaque(true);

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("0");
        jLabel49.setAlignmentX(1.0F);
        jLabel49.setOpaque(true);

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("0");
        jLabel50.setAlignmentX(1.0F);
        jLabel50.setOpaque(true);

        Time1Jogo8Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo8Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo8Label.setText("Time1");
        Time1Jogo8Label.setAlignmentX(1.0F);
        Time1Jogo8Label.setOpaque(true);

        Time2Jogo8Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo8Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo8Label.setText("Time1");
        Time2Jogo8Label.setAlignmentX(1.0F);
        Time2Jogo8Label.setOpaque(true);

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("0");
        jLabel53.setAlignmentX(1.0F);
        jLabel53.setOpaque(true);

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("0");
        jLabel54.setAlignmentX(1.0F);
        jLabel54.setOpaque(true);

        Time1Jogo12Label.setBackground(new java.awt.Color(255, 255, 255));
        Time1Jogo12Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time1Jogo12Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1Jogo12Label.setText("Time1");
        Time1Jogo12Label.setAlignmentX(1.0F);
        Time1Jogo12Label.setOpaque(true);

        Time2Jogo12Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo12Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo12Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo12Label.setText("Time1");
        Time2Jogo12Label.setAlignmentX(1.0F);
        Time2Jogo12Label.setOpaque(true);

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("0");
        jLabel57.setAlignmentX(1.0F);
        jLabel57.setOpaque(true);

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("0");
        jLabel58.setAlignmentX(1.0F);
        jLabel58.setOpaque(true);

        Time2Jogo14Label.setBackground(new java.awt.Color(255, 255, 255));
        Time2Jogo14Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time2Jogo14Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2Jogo14Label.setText("Time1");
        Time2Jogo14Label.setAlignmentX(1.0F);
        Time2Jogo14Label.setOpaque(true);

        jLabel60.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("0");
        jLabel60.setAlignmentX(1.0F);
        jLabel60.setOpaque(true);

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("0");
        jLabel61.setAlignmentX(1.0F);
        jLabel61.setOpaque(true);

        jLabel62.setBackground(new java.awt.Color(255, 255, 255));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("0");
        jLabel62.setAlignmentX(1.0F);
        jLabel62.setOpaque(true);

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("0");
        jLabel63.setAlignmentX(1.0F);
        jLabel63.setOpaque(true);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Oitavas de final");

        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Quartas de final");

        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Quartas de final");

        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Oitavas de final");

        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Semi final");

        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Semi final");

        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Final");

        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("3° Lugar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Time1Jogo1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(Time1Jogo9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(386, 386, 386)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(SimularButton)
                                                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel69)
                                                        .addGap(193, 193, 193)))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(160, 160, 160))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(Time2Jogo14Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(refazerSimulacaoButton)
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(avancarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                                        .addGap(7, 7, 7)
                                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(Time1Jogo11Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(Time2Jogo11Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                            .addComponent(Time1Jogo14Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(280, 280, 280)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(Time2Jogo15Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(Time1Jogo15Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(420, 420, 420)
                                                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel65)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(12, 12, 12)))
                                                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Time2Jogo5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time1Jogo5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time1Jogo6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time2Jogo6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time2Jogo7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time1Jogo7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time1Jogo8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Time2Jogo8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Time2Jogo10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Time2Jogo9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Time1Jogo10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Time1Jogo12Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Time2Jogo12Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(199, 199, 199))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time2Jogo1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel64))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time1Jogo4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time2Jogo4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time2Jogo3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time1Jogo2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time1Jogo3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Time2Jogo2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(204, 204, 204)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Time2Jogo13Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Time1Jogo13Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(116, 116, 116)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Time2Jogo16Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Time1Jogo16Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(139, 139, 139)
                                                    .addComponent(jLabel70)))))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FaseGruposLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel68)
                .addGap(378, 378, 378))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time1Jogo11Label)
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time2Jogo11Label)
                                    .addComponent(jLabel42))
                                .addGap(18, 18, 18)
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel68))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time1Jogo14Label)
                                    .addComponent(jLabel39)
                                    .addComponent(Time1Jogo13Label)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel70))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time2Jogo14Label)
                                    .addComponent(jLabel60)
                                    .addComponent(Time2Jogo13Label)
                                    .addComponent(jLabel61)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel66)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(26, 26, 26)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Time1Jogo9Label)
                                                    .addComponent(jLabel23)))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Time1Jogo1Label)
                                                    .addComponent(jLabel2)
                                                    .addComponent(Time1Jogo5Label)
                                                    .addComponent(jLabel36))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Time2Jogo1Label)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel64))
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Time2Jogo5Label)
                                                        .addComponent(jLabel40)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Time2Jogo9Label)
                                            .addComponent(jLabel22))
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Time1Jogo2Label)
                                                    .addComponent(jLabel6))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Time2Jogo2Label)
                                                    .addComponent(jLabel18)))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Time1Jogo16Label)
                                                    .addComponent(jLabel31)
                                                    .addComponent(Time1Jogo6Label)
                                                    .addComponent(jLabel46))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Time2Jogo16Label)
                                                        .addComponent(jLabel32))
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Time2Jogo6Label)
                                                        .addComponent(jLabel47))))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel69)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Time1Jogo3Label)
                                            .addComponent(jLabel19)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel49)
                                            .addComponent(Time1Jogo7Label))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time2Jogo3Label)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time1Jogo10Label)
                                    .addComponent(Time1Jogo12Label)
                                    .addComponent(jLabel57))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time2Jogo10Label)
                                    .addComponent(Time2Jogo12Label)
                                    .addComponent(jLabel58))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time1Jogo4Label)
                                    .addComponent(jLabel21)
                                    .addComponent(Time1Jogo8Label)
                                    .addComponent(jLabel53))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time2Jogo4Label)
                                    .addComponent(jLabel20)
                                    .addComponent(Time2Jogo8Label)
                                    .addComponent(jLabel54))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Time2Jogo7Label)
                                    .addComponent(jLabel50))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(FaseGruposLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Time1Jogo15Label)
                            .addComponent(jLabel63))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Time2Jogo15Label)
                            .addComponent(jLabel62))
                        .addGap(178, 178, 178)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avancarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refazerSimulacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularButtonActionPerformed
        simularFaseGrupo();
    }//GEN-LAST:event_SimularButtonActionPerformed

    private void refazerSimulacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refazerSimulacaoButtonActionPerformed
        TimeDAO.zerarClassificacaoGeral();
        this.grupos = GrupoDAO.listarGruposCompletos();
        this.campeonato = new Campeonato(grupos);
        simularFaseGrupo();
    }//GEN-LAST:event_refazerSimulacaoButtonActionPerformed

    private void avancarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avancarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSimularMataMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSimularMataMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSimularMataMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSimularMataMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSimularMataMata(GrupoDAO.listarGruposCompletos()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FaseGruposLabel;
    private javax.swing.JButton SimularButton;
    private javax.swing.JLabel Time1Jogo10Label;
    private javax.swing.JLabel Time1Jogo11Label;
    private javax.swing.JLabel Time1Jogo12Label;
    private javax.swing.JLabel Time1Jogo13Label;
    private javax.swing.JLabel Time1Jogo14Label;
    private javax.swing.JLabel Time1Jogo15Label;
    private javax.swing.JLabel Time1Jogo16Label;
    private javax.swing.JLabel Time1Jogo1Label;
    private javax.swing.JLabel Time1Jogo2Label;
    private javax.swing.JLabel Time1Jogo3Label;
    private javax.swing.JLabel Time1Jogo4Label;
    private javax.swing.JLabel Time1Jogo5Label;
    private javax.swing.JLabel Time1Jogo6Label;
    private javax.swing.JLabel Time1Jogo7Label;
    private javax.swing.JLabel Time1Jogo8Label;
    private javax.swing.JLabel Time1Jogo9Label;
    private javax.swing.JLabel Time2Jogo10Label;
    private javax.swing.JLabel Time2Jogo11Label;
    private javax.swing.JLabel Time2Jogo12Label;
    private javax.swing.JLabel Time2Jogo13Label;
    private javax.swing.JLabel Time2Jogo14Label;
    private javax.swing.JLabel Time2Jogo15Label;
    private javax.swing.JLabel Time2Jogo16Label;
    private javax.swing.JLabel Time2Jogo1Label;
    private javax.swing.JLabel Time2Jogo2Label;
    private javax.swing.JLabel Time2Jogo3Label;
    private javax.swing.JLabel Time2Jogo4Label;
    private javax.swing.JLabel Time2Jogo5Label;
    private javax.swing.JLabel Time2Jogo6Label;
    private javax.swing.JLabel Time2Jogo7Label;
    private javax.swing.JLabel Time2Jogo8Label;
    private javax.swing.JLabel Time2Jogo9Label;
    private javax.swing.JButton avancarButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton refazerSimulacaoButton;
    // End of variables declaration//GEN-END:variables

    private void simularFaseGrupo() {
        campeonato.simularPartidasFaseGrupo();
        grupos.forEach((grupo) -> {
            ArrayList<Time> times = grupo.getTimes();
            Collections.sort(times, new ClassificacaoComparator());
            switch (grupo.getId()) {
                case 'A' -> setResultadoSimulacao(grupoATable, times);
                case 'B' -> setResultadoSimulacao(grupoBTable, times);
                case 'C' -> setResultadoSimulacao(grupoCTable, times);
                case 'D' -> setResultadoSimulacao(grupoDTable, times);
                case 'E' -> setResultadoSimulacao(grupoETable, times);
                case 'F' -> setResultadoSimulacao(grupoFTable, times);
                case 'G' -> setResultadoSimulacao(grupoGTable, times);
                case 'H' -> setResultadoSimulacao(grupoHTable, times);
            }
        });
    }
    
    private void setValoresIniciaisTabelas() {
        grupos.forEach((grupo) -> {
            ArrayList<Time> times = grupo.getTimes();
            switch (grupo.getId()) {
                case 'A' -> setValorTabela(grupoATable, times);
                case 'B' -> setValorTabela(grupoBTable, times);
                case 'C' -> setValorTabela(grupoCTable, times);
                case 'D' -> setValorTabela(grupoDTable, times);
                case 'E' -> setValorTabela(grupoETable, times);
                case 'F' -> setValorTabela(grupoFTable, times);
                case 'G' -> setValorTabela(grupoGTable, times);
                case 'H' -> setValorTabela(grupoHTable, times);
            }
        });
    }
    
    private void setValorTabela(JTable tabela, ArrayList<Time> times) {        
        for (int i = 0; i < 4; i++) {
            tabela.setValueAt(times.get(i).getNome(), i, 0);
            tabela.setValueAt(0, i, 1);
            tabela.setValueAt(0, i, 2);
            tabela.setValueAt(0, i, 3);
        }
    }
    
    private void setResultadoSimulacao(JTable tabela, ArrayList<Time> times) {
        for (int i = 0; i < 4; i++) {
            tabela.setValueAt(times.get(i).getNome(), i, 0);
            tabela.setValueAt(times.get(i).getPontos(), i, 1);
            tabela.setValueAt(times.get(i).getGolPro(), i, 2);
            tabela.setValueAt(times.get(i).getSaldoGols(), i, 3);
        }
    }
}
